foreach file : [
    'allocator/arena.c',
    'allocator/bitmap.c',
    'allocator/freelist.c',
    'allocator/region.c',
    'ds/intrusivelist.c',
    'ds/linkedlist.c',
    'ds/ringbuffer.c',
    'error.c',
    'stdlib.c',
    'string.c',
]
    kernel_c_sources += files(project_root / 'lib' / file)
endforeach
